### ISSUE TITLE
Add .libsonnet extension

### ISSUE THREAD

**Issue by nikolay** [google/language-jsonnet#6]
Ksonnet is getting popular in the Kubernetes community and `.libsonnet` is being used as a file extension for libraries. Supporting it out of the box would be nice!

**Comment by nikolay** [comment]
Hmmm, obviously you support it already, but why isn't Atom highlighting then?!

**Comment by jolson490** [comment]
I was able to get Atom to apply the highlighting to `.libsonnet` files by adding the following to my `~/.atom/config.cson` file:
```
"*":
  core:
    customFileTypes:
      'source.jsonnet': [
        'libsonnet'
      ]
```

Reference info: https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition
