### ISSUE TITLE
Invalid regex: nothing to repeat

### ISSUE THREAD

**Issue by lildude** [google/language-jsonnet#9]
👋 I'm the lead maintainer of the https://github.com/github/linguist library which is used for language detection and providing the syntax highlighting for languages on GitHub.com, and we use this grammar.

Our grammar compiler has found a problem with your grammar which I thought I'd let you know about.

This regex is invalid as it has nothing to repeat at offset 43:

https://github.com/google/language-jsonnet/blob/ce5a40ccd339bbd6f7150205e619814b34d218a5/grammars/jsonnet.cson#L178

https://regex101.com/r/B1tYx6/1

This is the error our compiler reported:

Invalid regex in grammar: `source.jsonnet` (in `grammars/jsonnet.cson`) contains a malformed regex (regex "`\b[a-zA-Z_][a-z0-9A-Z_]*\s*(\([^`...": nothing to repeat (at offset 43))

**Comment by sparkprime** [comment]
Is offset 43 the `?` here:

```
\\b[a-zA-Z_][a-z0-9A-Z_]*\\s*(\\([^)]*\\))?\\s*+?::?:?'
                                          ^
```

**Comment by sparkprime** [comment]
Ah no i see, you have to unescape it and then it points at this `*+` issue

**Comment by sparkprime** [comment]
That `+` is supposed to be a literal `+` not a repeat operator, so I guess it needs a \\ before it:

```
\\b[a-zA-Z_][a-z0-9A-Z_]*\\s*(\\([^)]*\\))?\\s*\\+?::?:?
```

**Comment by sparkprime** [comment]
BTW your link to https://regex101.com/r/B1tYx6/1 needs to unescape it too
